spring:
  profile.active : dev, test, prod
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed-api
    username: root
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true


server:
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:123456}